# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seasonality' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Seasonality

	pod 'GoogleMaps'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'

  target 'SeasonalityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
